#!/bin/bash

# This script is used to activate the build environment.
# It adds this directory to the PATH and sets the prompt.

export OLD_PATH="${PATH}"
export PATH="$PWD/buildenv:${PATH}"
export BENV_PROJ_PATH="${PWD}"
export BENV_PATH="${PWD}/buildenv"
export OLD_PS1="${PS1}"
export PS1="\e[1;34m(\e[1;32mhexos-x86_64\e[1;34m)\e[0m ${OLD_PS1}"
chmod +x "${BENV_PATH}/hcc"
chmod -x "${BENV_PATH}/activate"
chmod +x "${BENV_PATH}/deactivate"
alias hcc="${BENV_PATH}/hcc"
alias deactivate="source ${BENV_PATH}/deactivate"
