#!/bin/bash

# This script is used to activate the build environment.
# It adds this directory to the PATH and sets the prompt.

chmod +x buildenv/hcc

export OLD_PATH="${PATH}"
export PATH="$PWD/buildenv:${PATH}"

export OLD_PS1="${PS1}"
export PS1="\e[1;34m(\e[1;32mhexos-x86_64\e[1;34m)\e[0m ${OLD_PS1}"
