#!/bin/bash

# This script is used to deactivate the build environment.
# It removes this directory from the PATH and unsets the prompt.

chmod -x buildenv/hcc

export PATH="${OLD_PATH}"
unset OLD_PATH

export PS1="${OLD_PS1}"
unset OLD_PS1
