#!/bin/bash

# This script is used to build the operating system.
# It calls the build script of the tcc compiler and the elf2hxe tool.

# The build script of the tcc compiler.
tcc -o /tmp/hcc_build $1
if [ $? -ne 0 ]; then
    echo "Error: tcc build script failed."
    exit 1
fi

# The elf2hxe tool.
elf2hxe /tmp/hcc_build $2
